//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Ensure unused imports are referenced.
var _ = metav1.Now

// DeepCopyInto copies all properties into another PowerPolicy.
func (in *PowerPolicy) DeepCopyInto(out *PowerPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PowerPolicy) DeepCopy() *PowerPolicy {
	if in == nil { return nil }
	out := new(PowerPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *PowerPolicyList) DeepCopyInto(out *PowerPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerPolicy, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *PowerPolicyList) DeepCopy() *PowerPolicyList {
	if in == nil { return nil }
	out := new(PowerPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *PowerPolicySpec) DeepCopyInto(out *PowerPolicySpec) {
	*out = *in
	in.Scope.DeepCopyInto(&out.Scope)
	in.Schedule.DeepCopyInto(&out.Schedule)
}

func (in *PowerPolicyStatus) DeepCopyInto(out *PowerPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
	if in.NextTransition != nil {
		in, out := &in.NextTransition, &out.NextTransition
		*out = (*in).DeepCopy()
	}
}

// DeepCopyInto for PowerOverride
func (in *PowerOverride) DeepCopyInto(out *PowerOverride) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PowerOverride) DeepCopy() *PowerOverride {
	if in == nil { return nil }
	out := new(PowerOverride)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerOverride) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *PowerOverrideList) DeepCopyInto(out *PowerOverrideList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerOverride, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *PowerOverrideList) DeepCopy() *PowerOverrideList {
	if in == nil { return nil }
	out := new(PowerOverrideList)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerOverrideList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *PowerOverrideSpec) DeepCopyInto(out *PowerOverrideSpec) {
	*out = *in
	in.Scope.DeepCopyInto(&out.Scope)
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

func (in *PowerOverrideStatus) DeepCopyInto(out *PowerOverrideStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

// DeepCopyInto for PowerTarget
func (in *PowerTarget) DeepCopyInto(out *PowerTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PowerTarget) DeepCopy() *PowerTarget {
	if in == nil { return nil }
	out := new(PowerTarget)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *PowerTargetList) DeepCopyInto(out *PowerTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerTarget, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *PowerTargetList) DeepCopy() *PowerTargetList {
	if in == nil { return nil }
	out := new(PowerTargetList)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *PowerTargetStatus) DeepCopyInto(out *PowerTargetStatus) {
	*out = *in
	if in.WinningRule != nil {
		in, out := &in.WinningRule, &out.WinningRule
		*out = new(RuleReference)
		**out = **in
	}
	if in.SuppressedRules != nil {
		in, out := &in.SuppressedRules, &out.SuppressedRules
		*out = make([]RuleReference, len(*in))
		copy(*out, *in)
	}
	if in.BlockReasons != nil {
		in, out := &in.BlockReasons, &out.BlockReasons
		*out = make([]BlockReasonSpec, len(*in))
		copy(*out, *in)
	}
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(SnapshotSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Ownership != nil {
		in, out := &in.Ownership, &out.Ownership
		*out = make([]OwnershipSpec, len(*in))
		copy(*out, *in)
	}
	if in.Savings != nil {
		in, out := &in.Savings, &out.Savings
		*out = new(SavingsSpec)
		**out = **in
	}
	if in.LastTransition != nil {
		in, out := &in.LastTransition, &out.LastTransition
		*out = (*in).DeepCopy()
	}
	if in.LastReconciliation != nil {
		in, out := &in.LastReconciliation, &out.LastReconciliation
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *SnapshotSpec) DeepCopyInto(out *SnapshotSpec) {
	*out = *in
	if in.ReplicaCount != nil {
		in, out := &in.ReplicaCount, &out.ReplicaCount
		*out = new(int32)
		**out = **in
	}
	if in.Suspended != nil {
		in, out := &in.Suspended, &out.Suspended
		*out = new(bool)
		**out = **in
	}
	if in.CapturedAt != nil {
		in, out := &in.CapturedAt, &out.CapturedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopyInto for PowerAuditEvent
func (in *PowerAuditEvent) DeepCopyInto(out *PowerAuditEvent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *PowerAuditEvent) DeepCopy() *PowerAuditEvent {
	if in == nil { return nil }
	out := new(PowerAuditEvent)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerAuditEvent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *PowerAuditEventList) DeepCopyInto(out *PowerAuditEventList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerAuditEvent, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *PowerAuditEventList) DeepCopy() *PowerAuditEventList {
	if in == nil { return nil }
	out := new(PowerAuditEventList)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerAuditEventList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

// DeepCopyInto for PowerSchedule
func (in *PowerSchedule) DeepCopyInto(out *PowerSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *PowerSchedule) DeepCopy() *PowerSchedule {
	if in == nil { return nil }
	out := new(PowerSchedule)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *PowerScheduleList) DeepCopyInto(out *PowerScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerSchedule, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *PowerScheduleList) DeepCopy() *PowerScheduleList {
	if in == nil { return nil }
	out := new(PowerScheduleList)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

// Shared deep copy helpers
func (in *PolicyScope) DeepCopyInto(out *PolicyScope) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceLabels != nil {
		in, out := &in.NamespaceLabels, &out.NamespaceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in { (*out)[key] = val }
	}
	if in.WorkloadNames != nil {
		in, out := &in.WorkloadNames, &out.WorkloadNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WorkloadLabels != nil {
		in, out := &in.WorkloadLabels, &out.WorkloadLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in { (*out)[key] = val }
	}
}

func (in *PolicySchedule) DeepCopyInto(out *PolicySchedule) {
	*out = *in
	if in.Windows != nil {
		in, out := &in.Windows, &out.Windows
		*out = make([]TimeWindowSpec, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *TimeWindowSpec) DeepCopyInto(out *TimeWindowSpec) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

func (in *PowerScheduleSpec) DeepCopyInto(out *PowerScheduleSpec) {
	*out = *in
	if in.Windows != nil {
		in, out := &in.Windows, &out.Windows
		*out = make([]TimeWindowSpec, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

// DeepCopyInto for PowerNamespaceGroup
func (in *PowerNamespaceGroup) DeepCopyInto(out *PowerNamespaceGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *PowerNamespaceGroup) DeepCopy() *PowerNamespaceGroup {
	if in == nil { return nil }
	out := new(PowerNamespaceGroup)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerNamespaceGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *PowerNamespaceGroupList) DeepCopyInto(out *PowerNamespaceGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerNamespaceGroup, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *PowerNamespaceGroupList) DeepCopy() *PowerNamespaceGroupList {
	if in == nil { return nil }
	out := new(PowerNamespaceGroupList)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerNamespaceGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *PowerNamespaceGroupSpec) DeepCopyInto(out *PowerNamespaceGroupSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}


// DeepCopyInto is an autogenerated deepcopy function.
func (in *PowerNotificationChannel) DeepCopyInto(out *PowerNotificationChannel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *PowerNotificationChannel) DeepCopy() *PowerNotificationChannel {
	if in == nil {
		return nil
	}
	out := new(PowerNotificationChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *PowerNotificationChannel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *PowerNotificationChannelList) DeepCopyInto(out *PowerNotificationChannelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerNotificationChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *PowerNotificationChannelList) DeepCopy() *PowerNotificationChannelList {
	if in == nil {
		return nil
	}
	out := new(PowerNotificationChannelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *PowerNotificationChannelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *PowerNotificationChannelSpec) DeepCopyInto(out *PowerNotificationChannelSpec) {
	*out = *in
	if in.URLFrom != nil {
		in, out := &in.URLFrom, &out.URLFrom
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceFilter != nil {
		in, out := &in.NamespaceFilter, &out.NamespaceFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *PowerNotificationChannelSpec) DeepCopy() *PowerNotificationChannelSpec {
	if in == nil {
		return nil
	}
	out := new(PowerNotificationChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *PowerNotificationChannelStatus) DeepCopyInto(out *PowerNotificationChannelStatus) {
	*out = *in
	if in.LastNotification != nil {
		in, out := &in.LastNotification, &out.LastNotification
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *PowerNotificationChannelStatus) DeepCopy() *PowerNotificationChannelStatus {
	if in == nil {
		return nil
	}
	out := new(PowerNotificationChannelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}
