apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: powerauditevents.power.aura.sh
spec:
  conversion:
    strategy: None
  group: power.aura.sh
  names:
    kind: PowerAuditEvent
    listKind: PowerAuditEventList
    plural: powerauditevents
    shortNames:
    - pae
    singular: powerauditevent
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              action:
                type: string
              actor:
                type: string
              reason:
                type: string
              result:
                type: string
              ruleName:
                type: string
              target:
                properties:
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                type: object
              timestamp:
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
